const Homeproduct =
[
    {
        id: 1,
        Name: 'Sumsung TV',
        price: '26',
        image: 'image/p1.webp',
        cat: 'tv',
        type: 'new',
    },
    {
        id:14,
        Name:"Zebronics",
        price:"34",
        image:"image/p14.png",
        cat:"tv",
        type:"new"
    },
    {
        id: 15,
        Name: 'Sumsung TV',
        price: '26',
        image: 'image/p15.webp',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 13,
        Name: 'Sumsung TV',
        price: '26',
        image: 'image/p13.jpeg',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 5,
        Name: 'UV TV',
        price: '26',
        image: '',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 6,
        Name: 'Dell',
        price: '96',
        image: '',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 7,
        Name: 'Intex',
        price: '96',
        image: '',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 8,
        Name: 'Lenovo',
        price: '96',
        image: '',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 9,
        Name: 'HP',
        price: '96',
        image: '',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 10,
        Name: 'Toshiba',
        price: '96',
        image: '',
        cat: 'laptop',
        type: 'new',
    },

    {
        id: 11,
        Name: 'product3',
        price: '236',
        image: 'image/p3.webp',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 12,
        Name: 'product4',
        price: '636',
        image: 'image/p9.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 13,
        Name: 'product5',
        price: '98',
        image: 'image/p4.webp',
        cat: 'speaker',
        type: 'featured',
    },
    {
        id: 14,
        Name: 'product6',
        price: '59',
        image: 'image/p5.webp',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 15,
        Name: 'product7',
        price: '956',
        image: 'image/p10.jpg',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 16,
        Name: 'product8',
        price: '389',
        image: 'image/p11.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 17,
        Name: 'product9',
        price: '67',
        image: 'image/p6.webp',
        cat: 'phone',
        type: 'top',
    },
    {
        id: 18,
        Name: 'product10',
        price: '76',
        image: 'image/p7.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 19,
        Name: 'product11',
        price: '87',
        image: 'image/p8.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 19,
        Name: 'product12',
        price: '807',
        image: 'image/p12.jpg',
        cat: 'speaker',
        type: 'top',
    },
]
export default Homeproduct